// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDGtHUBEiEvB7txoHRMUy8TARehsMafh2s',
    appId: '1:5315376274:web:7658159968512b5612224b',
    messagingSenderId: '5315376274',
    projectId: 'pln-project-a6867',
    authDomain: 'pln-project-a6867.firebaseapp.com',
    databaseURL: 'https://pln-project-a6867-default-rtdb.firebaseio.com',
    storageBucket: 'pln-project-a6867.firebasestorage.app',
    measurementId: 'G-8WDSJRNJ6K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDmd_NpbIyw6X5C7YUmTAzMff6QhosyQeU',
    appId: '1:5315376274:android:9b40fc81605ea2b012224b',
    messagingSenderId: '5315376274',
    projectId: 'pln-project-a6867',
    databaseURL: 'https://pln-project-a6867-default-rtdb.firebaseio.com',
    storageBucket: 'pln-project-a6867.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA6He3qkJm_dIw7k7bmJ9OpurIXYV0iSSo',
    appId: '1:5315376274:ios:4add85b642100fc112224b',
    messagingSenderId: '5315376274',
    projectId: 'pln-project-a6867',
    databaseURL: 'https://pln-project-a6867-default-rtdb.firebaseio.com',
    storageBucket: 'pln-project-a6867.firebasestorage.app',
    iosBundleId: 'com.example.frontend',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA6He3qkJm_dIw7k7bmJ9OpurIXYV0iSSo',
    appId: '1:5315376274:ios:4add85b642100fc112224b',
    messagingSenderId: '5315376274',
    projectId: 'pln-project-a6867',
    databaseURL: 'https://pln-project-a6867-default-rtdb.firebaseio.com',
    storageBucket: 'pln-project-a6867.firebasestorage.app',
    iosBundleId: 'com.example.frontend',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDGtHUBEiEvB7txoHRMUy8TARehsMafh2s',
    appId: '1:5315376274:web:41798b01ca384fcc12224b',
    messagingSenderId: '5315376274',
    projectId: 'pln-project-a6867',
    authDomain: 'pln-project-a6867.firebaseapp.com',
    databaseURL: 'https://pln-project-a6867-default-rtdb.firebaseio.com',
    storageBucket: 'pln-project-a6867.firebasestorage.app',
    measurementId: 'G-PH2C37SCS0',
  );
}
